function Inversiones() {
  return (
    <section className="padded">
        <div className="container">
            <h2>Inversiones</h2>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Incidunt illum quod suscipit voluptatum nemo? Animi iste sapiente eos architecto officiis! Earum minima doloribus labore iste qui eligendi alias perspiciatis repellat ipsum ad. Neque ut, nam veniam facere rem quasi ipsum laudantium debitis in incidunt natus minima deserunt praesentium quas, maxime illo odio aspernatur sunt. Architecto modi beatae eius, sequi harum nesciunt cumque delectus. Excepturi tempore velit ex fugiat harum quaerat earum nobis itaque voluptatibus iusto. Voluptates aperiam blanditiis minima sapiente!</p>
            <p>Illo vel dolor necessitatibus ad eos temporibus quaerat. Delectus tempore excepturi eligendi recusandae atque possimus accusamus nemo eius consectetur accusantium quasi explicabo voluptate officia quisquam consequuntur, voluptates assumenda. Mollitia, aspernatur? Laboriosam perferendis minus distinctio maxime exercitationem magnam nostrum autem impedit assumenda, hic voluptates, doloremque blanditiis incidunt dolorem! Illo hic quasi voluptas error vitae, mollitia incidunt magnam veniam nihil amet provident libero eaque facere exercitationem dolor repudiandae repellendus. Aspernatur magnam, architecto, aliquid delectus laboriosam ipsa odio fugiat doloribus qui dolore voluptatibus!</p>
            <p>Porro, est sapiente. Maxime perspiciatis quis natus voluptatem quaerat explicabo sequi libero animi voluptas optio unde fugit reiciendis veniam, pariatur illum cum laborum! Culpa dolore, excepturi saepe ex voluptate ratione inventore esse! Labore incidunt cupiditate vitae atque tempore facilis voluptate asperiores fugit, obcaecati optio dolore sequi debitis iure tenetur deleniti mollitia iste eveniet harum assumenda esse cumque quae omnis! Minima vero quod amet quisquam, eaque exercitationem inventore. Doloribus sint culpa architecto, animi quibusdam laboriosam nam similique blanditiis eaque repellendus distinctio.</p>
            <p>Magnam veniam distinctio nihil voluptatum nisi, velit officiis non reprehenderit, iusto dolor quidem commodi? Veniam numquam, sapiente totam vel quibusdam nemo minus commodi nobis dolore nam illo ducimus officiis ab illum ex quaerat asperiores earum possimus tenetur fuga blanditiis esse natus in deleniti. Incidunt quae repellat magni architecto fugiat nostrum dolorum, delectus sapiente distinctio dolor ipsam rerum obcaecati est aspernatur qui possimus ducimus iste nemo, unde, cum temporibus. Voluptate neque molestiae aliquam qui soluta velit repudiandae facere aliquid, consectetur quis?</p>
            <p>Neque eum facere reprehenderit nemo natus aspernatur totam deleniti ipsam a asperiores. Soluta inventore sint consequatur suscipit molestias adipisci libero eaque quae aspernatur. Officiis nobis nihil laboriosam blanditiis, dolorem quod animi at, saepe veritatis necessitatibus qui, nesciunt unde iste harum reiciendis molestiae consectetur earum hic corporis? Vitae dignissimos odio omnis nostrum sunt numquam saepe ex ducimus harum, nobis veritatis aliquid. Reiciendis sequi blanditiis at voluptate ea? Aliquid facere, quibusdam sed officiis eos eius earum error ipsum itaque beatae corporis dolor?</p>
            <p>Reprehenderit quisquam inventore cupiditate natus officiis sed error rem deserunt quas tenetur laboriosam quae, magni doloremque quo illum a dolorem nostrum saepe deleniti ratione! Earum nemo quas quaerat ut dolore molestias debitis distinctio illum possimus atque voluptate at facere, recusandae corporis reiciendis ducimus tempore a incidunt ipsam nostrum quae eum in fugiat? Quibusdam nulla atque nihil optio. Magni, illo? Fugiat, aut. Blanditiis cumque asperiores, commodi ipsa dolorem doloribus nemo mollitia dicta! Libero, sunt labore et eum nemo in modi enim!</p>
        </div>
    </section>
  )
}

export default Inversiones